#include "cxxopts.hpp"
#include "EstimParam.hpp"
#include "ModelChoice.hpp"
#include "cxxopts.hpp"
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/eigen.h>
#include <list>

const cxxopts::ParseResult & parseopt(std::string stropts) {
    std::istringstream ss(stropts);
    std::string arg;
    std::list<std::string> ls;
    std::vector<char*> v;
    while (ss >> arg)
    {
        ls.push_back(arg); 
        v.push_back(const_cast<char*>(ls.back().c_str()));
    }
    v.push_back(0);  // need terminating null pointer

    size_t nref;
    cxxopts::Options options("", " - ABC Random Forest - Model choice or parameter estimation command line options");

    options
        .positional_help("[optional args]")
        .show_positional_help();

    options.add_options()
        ("o,output","Prefix output (modelchoice_out or estimparam_out by default)",cxxopts::value<std::string>())
        ("n,nref","Number of samples, 0 means all",cxxopts::value<size_t>()->default_value("0"))
        ("m,minnodesize","Minimal node size. 0 means 1 for classification or 5 for regression",cxxopts::value<size_t>()->default_value("0"))
        ("t,ntree","Number of trees",cxxopts::value<size_t>()->default_value("500"))
        ("j,threads","Number of threads, 0 means all",cxxopts::value<size_t>()->default_value("0"))
        ("s,seed","Seed, generated by default",cxxopts::value<size_t>()->default_value("0"))
        ("c,noisecolumns","Number of noise columns",cxxopts::value<size_t>()->default_value("5"))
        ("nolinear","Disable LDA for model choice or PLS for parameter estimation")
        ("chosenscen","Chosen scenario (mandatory for parameter estimation)", cxxopts::value<size_t>())
        ("noob","number of oob testing samples (mandatory for parameter estimation)",cxxopts::value<size_t>())
        ("parameter","name of the parameter of interest (mandatory for parameter estimation)",cxxopts::value<std::string>())
        ("g,groups","Groups of models",cxxopts::value<std::string>())
        ("help", "Print help")
        ;
    int argc = (int)v.size();
    char **argv = v.data();

    return options.parse(argc,argv);
}

ModelChoiceResults ModelChoice_fun_py(Reftable &reftable,
                                   std::vector<double> statobs,
                                   std::string options,
                                   bool quiet = false) {
    return ModelChoice_fun(reftable,statobs,parseopt(options),quiet);
}

EstimParamResults EstimParam_fun_py(Reftable &reftable,
                                   std::vector<double> statobs,
                                   std::string options,
                                   bool quiet = false) {
    return EstimParam_fun(reftable,statobs,parseopt(options),quiet);
}

namespace py = pybind11;
using namespace Eigen;

PYBIND11_MODULE(pyabcranger, m) {
    py::class_<Reftable>(m,"reftable")
        .def(py::init<int,
                       std::vector<size_t>,
                       std::vector<size_t>,
                       std::vector<string>,
                       std::vector<string>,
                       MatrixXd,
                       MatrixXd,
                       std::vector<double>>());
    py::class_<ModelChoiceResults>(m,"modelchoice_results");
    py::class_<EstimParamResults>(m,"estimparam_results");

    m.def("modelchoice", &ModelChoice_fun_py);
    m.def("estimparam", &EstimParam_fun_py);
}