[build-system]
requires = ["setuptools>=40.8.0", "wheel","cmaketools","cmake","ninja","vswhere"]

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_24"
skip = "cp27-* cp35-* pp*  *-manylinux_i686 *-win32"
test-command = "pytest {project}/test/test-pyabcranger.py -v"
before-test = "pip install pytest h5py"
test-requires = ["pytest", "h5py"]

[tool.cibuildwheel.linux]
before-all = "bash presetup.sh"
environment = { CC = "gcc-9", CXX = "g++-9"}

[tool.cibuildwheel.windows]
before-build = "pip install cmaketools cmake ninja vswhere"